### ISSUE TITLE
wish list

### ISSUE THREAD

**Issue by bambooforest** [clld/phoible#12]
add unique languages on 

http://phoible.org/inventories

"Showing 1 to 100 of 2,155 inventories (1672 languages)"

or maybe even

"Showing 1 to 100 of 2,155 doculects (1672 languages)"

**Comment by xrotwang** [comment]
The text 

> Showing 1 to 100 of 2,155 entries

is created by the javascript library which implements the tables. But we could add some explanation above, e.g.

> PHOIBLE comprises phoneme inventories for 2,155 doculects representing 1672 distinct languages.

**Comment by bambooforest** [comment]
I thought maybe the Javascript call could also just count the number of distinct ISO/Glottolog codes in the table. But sure, this is also fine and easier. It can also wait until phoible version 2017. I just noticed that "2155 entries" has confused a few people.

**Comment by xrotwang** [comment]
Oh, the javascript call is just a big "insert the table here", nothing I have too much control over.
