### ISSUE TITLE
Contributors text gets cut off

### ISSUE THREAD

**Issue by bambooforest** [clld/phoible#19]
@xrotwang -- i noticed here the last two contributors' text is cut off:

https://phoible.org/contributors

**Comment by xrotwang** [comment]
@bambooforest that's already the case in https://github.com/bambooforest/phoible-scripts/blob/master/to_cldf/cldf/contributors.csv#L11
So would need to be fixed there first.

**Comment by bambooforest** [comment]
D'oh. Sorry!

**Comment by bambooforest** [comment]
@xrotwang -- fixed in the CLDF dump. needs updating on the website (reopening). but hold off until decisions are made here: https://github.com/phoible/dev/issues/219
