### ISSUE TITLE
Rendering issue on the landing page

### ISSUE THREAD

**Issue by macleginn** [clld/phoible#24]
I see this (in Chrome):

![image](https://user-images.githubusercontent.com/4831042/104182702-83f94880-5419-11eb-810c-67f6213beea1.png)

Closing curly braces probably shouldn't be there.

**Comment by bambooforest** [comment]
Good catch. The text is also outdated, e.g.

Moran & Blasi, Cross-linguistic comparison of complexity measures in phonological systems, forthcoming

is published and this is a more suitable URL for pointing to published research that uses phoible:

https://scholar.google.com/scholar?oi=bibs&hl=en&cites=576981116309388928&as_sdt=5

Also on our list is to make a link to the FAQ for users:

http://phoible.github.io/faq/

**Comment by xrotwang** [comment]
Problem is caused by the bibtex formatting here https://github.com/clld/phoible/blob/9539cacc5d50343cc03a9e2788c1b60956275db5/phoible/scripts/util.py#L102

**Comment by bambooforest** [comment]
Hmm, I think it's the missing comma here:

https://github.com/clld/phoible/blob/9539cacc5d50343cc03a9e2788c1b60956275db5/phoible/scripts/util.py#L84

and `= jan` is probably also bad.
