### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by bambooforest** [clld/phoible#9]
http://phoible.org/parameters/D90087B832A91083C733048A0EA8614B#1/11/124

on the wikipedia "W" symbol, resolves to:

http://en.wikipedia.org//www.mediawiki.org/

**Comment by xrotwang** [comment]
This happens 47 times:
```
phoible=# select count(*) from parameter where jsondata like '%mediawiki%';
-[ RECORD 1 ]
count | 47
```

**Comment by xrotwang** [comment]
Fortunately it is very specific, so should be a simple db migration:
```
phoible=# select count(*) from parameter where jsondata = '{"wikipedia_url": "http://en.wikipedia.org//www.mediawiki.org/"}';
-[ RECORD 1 ]
count | 47
```
